using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.Migrations;

[DbContext(typeof(FinancialIngestionDbContext))]
[Migration("20260729120000_AddCyclicalWavesPsVisualization")]
public partial class AddCyclicalWavesPsVisualization : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(name: "CompanyPsGaugeSnapshots", columns: table => new
        {
            Id = table.Column<Guid>(type: "uuid", nullable: false), CompanyId = table.Column<Guid>(type: "uuid", nullable: false), SourceCompanyIsin = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false), ProviderName = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false), ObservationDate = table.Column<DateOnly>(type: "date", nullable: false),
            TtmPsRatio = table.Column<decimal>(type: "numeric(28,14)", precision: 28, scale: 14, nullable: false), ForwardPsRatio = table.Column<decimal>(type: "numeric(28,14)", precision: 28, scale: 14, nullable: false), GaugeClose = table.Column<decimal>(type: "numeric(28,14)", precision: 28, scale: 14, nullable: false), BoundaryStart = table.Column<decimal>(type: "numeric(28,14)", precision: 28, scale: 14, nullable: false), BoundaryMin = table.Column<decimal>(type: "numeric(28,14)", precision: 28, scale: 14, nullable: false), BoundaryAverage = table.Column<decimal>(type: "numeric(28,14)", precision: 28, scale: 14, nullable: false), BoundaryMax = table.Column<decimal>(type: "numeric(28,14)", precision: 28, scale: 14, nullable: false), BoundaryEnd = table.Column<decimal>(type: "numeric(28,14)", precision: 28, scale: 14, nullable: false),
            BucketA = table.Column<long>(type: "bigint", nullable: false), BucketB = table.Column<long>(type: "bigint", nullable: false), BucketC = table.Column<long>(type: "bigint", nullable: false), BucketD = table.Column<long>(type: "bigint", nullable: false), BucketE = table.Column<long>(type: "bigint", nullable: false), BucketF = table.Column<long>(type: "bigint", nullable: false), BucketTotal = table.Column<long>(type: "bigint", nullable: false), ProviderSymbol = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: true), GaugeFetchedAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false), CurrentValuesFetchedAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false), LastSyncedAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false), CompletenessStatus = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false), GaugeRenderabilityStatus = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false), QualityStatus = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false), QualityWarningsJson = table.Column<string>(type: "character varying(4096)", maxLength: 4096, nullable: false), GaugePayloadHash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false), CurrentValuesPayloadHash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false), NormalizedSnapshotHash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false), FirstSeenAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
        }, constraints: table => { table.PrimaryKey("PK_CompanyPsGaugeSnapshots", x => x.Id); table.ForeignKey("FK_CompanyPsGaugeSnapshots_Companies_CompanyId", x => x.CompanyId, "Companies", "Id", onDelete: ReferentialAction.Restrict); });
        migrationBuilder.CreateTable(name: "CompanyPsHistoryPoints", columns: table => new
        {
            Id = table.Column<Guid>(type: "uuid", nullable: false), CompanyId = table.Column<Guid>(type: "uuid", nullable: false), SourceCompanyIsin = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false), ProviderName = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false), ProviderPointId = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false), ObservationDate = table.Column<DateOnly>(type: "date", nullable: false), PsRatio = table.Column<decimal>(type: "numeric(28,14)", precision: 28, scale: 14, nullable: false), IsActiveInLatestSuccessfulSeries = table.Column<bool>(type: "boolean", nullable: false), FirstSeenAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false), LastSeenAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false), LastSeenInSuccessfulSeriesAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true), SourcePayloadHash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false)
        }, constraints: table => { table.PrimaryKey("PK_CompanyPsHistoryPoints", x => x.Id); table.ForeignKey("FK_CompanyPsHistoryPoints_Companies_CompanyId", x => x.CompanyId, "Companies", "Id", onDelete: ReferentialAction.Restrict); });
        migrationBuilder.CreateTable(name: "CompanyPsSeriesSyncStates", columns: table => new
        {
            Id = table.Column<Guid>(type: "uuid", nullable: false), CompanyId = table.Column<Guid>(type: "uuid", nullable: false), ProviderName = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false), SourceCompanyIsin = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false), DeclaredFirstHistoryDate = table.Column<DateOnly>(type: "date", nullable: true), DeclaredLastHistoryDate = table.Column<DateOnly>(type: "date", nullable: true), DeclaredHistoryCount = table.Column<long>(type: "bigint", nullable: true), ActualFirstHistoryDate = table.Column<DateOnly>(type: "date", nullable: true), ActualLastHistoryDate = table.Column<DateOnly>(type: "date", nullable: true), ActualHistoryCount = table.Column<long>(type: "bigint", nullable: true), NormalizedLatestSuccessfulSeriesHash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true), LastSuccessfulSnapshotId = table.Column<Guid>(type: "uuid", nullable: true), LastSuccessfulSnapshotDate = table.Column<DateOnly>(type: "date", nullable: true), LastGaugeSuccessAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true), LastCurrentValuesSuccessAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true), LastHistorySuccessAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true), LastGaugeAttemptAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true), LastCurrentValuesAttemptAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true), LastHistoryAttemptAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true), LastCompleteHistoryRefreshAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true), ConsecutiveGaugeFailures = table.Column<int>(type: "integer", nullable: false), ConsecutiveCurrentValuesFailures = table.Column<int>(type: "integer", nullable: false), ConsecutiveHistoryFailures = table.Column<int>(type: "integer", nullable: false), LastWarningCodesJson = table.Column<string>(type: "character varying(4096)", maxLength: 4096, nullable: false), LastErrorCode = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true), BackfillCompleted = table.Column<bool>(type: "boolean", nullable: false), NextEligibleHistoryRefreshAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true), LastSuccessfulCorrelationId = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: true)
        }, constraints: table => { table.PrimaryKey("PK_CompanyPsSeriesSyncStates", x => x.Id); table.ForeignKey("FK_CompanyPsSeriesSyncStates_Companies_CompanyId", x => x.CompanyId, "Companies", "Id", onDelete: ReferentialAction.Restrict); });
        migrationBuilder.CreateIndex("IX_CompanyPsGaugeSnapshots_CompanyId_GaugeRenderabilityStatus_ObservationDate", "CompanyPsGaugeSnapshots", new[] { "CompanyId", "GaugeRenderabilityStatus", "ObservationDate" });
        migrationBuilder.CreateIndex("IX_CompanyPsGaugeSnapshots_ProviderName_CompanyId_ObservationDate", "CompanyPsGaugeSnapshots", new[] { "ProviderName", "CompanyId", "ObservationDate" }, unique: true);
        migrationBuilder.CreateIndex("IX_CompanyPsHistoryPoints_CompanyId_IsActiveInLatestSuccessfulSeries_ObservationDate_ProviderPointId", "CompanyPsHistoryPoints", new[] { "CompanyId", "IsActiveInLatestSuccessfulSeries", "ObservationDate", "ProviderPointId" });
        migrationBuilder.CreateIndex("IX_CompanyPsHistoryPoints_ProviderName_CompanyId_ProviderPointId", "CompanyPsHistoryPoints", new[] { "ProviderName", "CompanyId", "ProviderPointId" }, unique: true);
        migrationBuilder.CreateIndex("IX_CompanyPsSeriesSyncStates_ProviderName_CompanyId", "CompanyPsSeriesSyncStates", new[] { "ProviderName", "CompanyId" }, unique: true);
        migrationBuilder.CreateTable(name: "CompanyPsVisualizationLeases", columns: table => new
        {
            LeaseName = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
            Owner = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
            ExpiresAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
            UpdatedAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
        }, constraints: table => table.PrimaryKey("PK_CompanyPsVisualizationLeases", x => x.LeaseName));
    }
    protected override void Down(MigrationBuilder migrationBuilder) { migrationBuilder.DropTable("CompanyPsVisualizationLeases"); migrationBuilder.DropTable("CompanyPsGaugeSnapshots"); migrationBuilder.DropTable("CompanyPsHistoryPoints"); migrationBuilder.DropTable("CompanyPsSeriesSyncStates"); }
}
