// <auto-generated />
using System;
using FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.Migrations
{
    [DbContext(typeof(FinancialIngestionDbContext))]
    [Migration("20260602041327_AddActorWatchlists")]
    partial class AddActorWatchlists
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.CodalDbSyncStateRow", b =>
                {
                    b.Property<string>("Dataset")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LastRunCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastRunStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSyncedModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Dataset");

                    b.ToTable("CodalDbSyncStates", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.DailyIndexSnapshotRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ChangePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("High")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Low")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("TradingDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TradingInstrumentId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("TradingInstrumentId");

                    b.HasIndex("ProviderName", "TradingInstrumentId", "TradingDate")
                        .IsUnique();

                    b.ToTable("DailyIndexSnapshots", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.DailyInstrumentTradeRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ClosingPrice")
                        .HasColumnType("numeric");

                    b.Property<long>("ExternalTradeId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("LastTradedPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MarketValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceChange")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceYesterday")
                        .HasColumnType("numeric");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SourceInsertedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalCapital")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalTransactions")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("TradingDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TradingInstrumentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProviderName", "ExternalTradeId")
                        .IsUnique();

                    b.HasIndex("TradingInstrumentId", "TradingDate");

                    b.ToTable("DailyInstrumentTrades", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.DataSyncRunRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dataset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProcessedRecords")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourcePayloadChecksum")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("ProviderSyncRuns", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.DerivedMetricRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CalculationPolicyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DependencyEvidenceJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSynchronizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetricCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MetricVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceEvidenceJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId", "MetricCode", "MetricVersion", "CalculationPolicyVersion", "PeriodEnd")
                        .IsUnique();

                    b.ToTable("DerivedMetrics", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.FeatureComputationJobRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FeatureCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FeatureVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("SymbolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("FeatureComputationJobs", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.FeatureDefinitionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DependenciesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeatureCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FeatureVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("InputSchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("MaximumValue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinimumValue")
                        .HasColumnType("numeric");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RequiredObservationWindow")
                        .HasColumnType("integer");

                    b.Property<string>("StrategyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureCode", "FeatureVersion")
                        .IsUnique();

                    b.ToTable("FeatureDefinitions", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.FeatureSnapshotRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DependencyEvidenceJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeatureCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FeatureVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("InputFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("LastSynchronizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceEvidenceJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId", "FeatureCode", "FeatureVersion", "PolicyVersion", "PeriodEnd", "InputFingerprint")
                        .IsUnique();

                    b.ToTable("FeatureSnapshots", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.IntradayIndexSnapshotRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ChangePercent")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ExternalSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SourceChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("TradingDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TradingInstrumentId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("TradingTime")
                        .HasColumnType("time without time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProviderName", "ExternalSnapshotId")
                        .IsUnique();

                    b.HasIndex("TradingInstrumentId", "TradingDate");

                    b.ToTable("IntradayIndexSnapshots", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.IntradayTradeSnapshotRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ClosingPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ExternalSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LastTradedPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceChange")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceYesterday")
                        .HasColumnType("numeric");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalCapital")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalTransactions")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("TradingDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TradingInstrumentId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("TradingTime")
                        .HasColumnType("time without time zone");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProviderName", "ExternalSnapshotId")
                        .IsUnique();

                    b.HasIndex("TradingInstrumentId", "ReceivedAt");

                    b.ToTable("IntradayTradeSnapshots", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.LatestMarketQuoteRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AsOf")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LatestPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceChangePercentage")
                        .HasColumnType("numeric");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TradingInstrumentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TradingInstrumentId");

                    b.HasIndex("ProviderName", "TradingInstrumentId")
                        .IsUnique();

                    b.ToTable("LatestMarketQuotes", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.MetricRecalculationRequestRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceDataset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourcePayloadChecksum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.HasIndex("SourceDataset", "SourcePayloadChecksum")
                        .IsUnique();

                    b.ToTable("MetricRecalculationRequests", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.MissingAnswerFeedbackRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AffectedDataCodeOrName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Context")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly>("DateBucket")
                        .HasColumnType("date");

                    b.Property<int>("FrequencyCount")
                        .HasColumnType("integer");

                    b.Property<string>("QueryHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RequestedMetricCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SymbolCountMatched")
                        .HasColumnType("integer");

                    b.Property<int>("SymbolCountTotal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("Classification");

                    b.HasIndex("DateBucket");

                    b.HasIndex("RequestedMetricCode");

                    b.HasIndex("SubmittedAt");

                    b.HasIndex("ActorId", "QueryHashSha256", "Classification", "DateBucket")
                        .IsUnique();

                    b.ToTable("MissingAnswerFeedbacks", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.NormalizedCompanyRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyIsin")
                        .HasColumnType("text");

                    b.Property<string>("CompanySymbol")
                        .HasColumnType("text");

                    b.Property<string>("ExternalCompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IndustryId")
                        .HasColumnType("uuid");

                    b.Property<string>("InstrumentCode")
                        .HasColumnType("text");

                    b.Property<string>("InstrumentRefPlaceholder")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSynchronizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEnglish")
                        .HasColumnType("text");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SourceModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SymbolIsin")
                        .HasColumnType("text");

                    b.Property<string>("TseSymbol")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("IndustryId");

                    b.HasIndex("MarketId");

                    b.HasIndex("ProviderName", "ExternalCompanyId")
                        .IsUnique();

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.NormalizedFinancialStatementLineItemRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FinancialStatementId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetricCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FinancialStatementId", "MetricCode")
                        .IsUnique();

                    b.ToTable("FinancialStatementLineItems", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.NormalizedFinancialStatementRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalCompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalStatementId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSynchronizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourcePayloadChecksum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatementType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProviderName", "StatementType");

                    b.HasIndex("ProviderName", "ExternalStatementId", "StatementType")
                        .IsUnique();

                    b.ToTable("FinancialStatements", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.NormalizedIndustryGroupRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSynchronizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProviderName", "ExternalId")
                        .IsUnique();

                    b.ToTable("IndustryGroups", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.NormalizedIndustryRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSynchronizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProviderName", "ExternalId")
                        .IsUnique();

                    b.ToTable("Industries", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.NormalizedMarketRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSynchronizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProviderName", "ExternalId")
                        .IsUnique();

                    b.ToTable("Markets", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.NormalizedMonthlyReportLineItemRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MonthlyReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ProductionQuantity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SalesAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SalesQuantity")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MonthlyReportId", "ProductCode")
                        .IsUnique();

                    b.ToTable("MonthlyReportLineItems", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.NormalizedMonthlyReportRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalCompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalReportId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSynchronizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourcePayloadChecksum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProviderName", "ExternalReportId")
                        .IsUnique();

                    b.ToTable("MonthlyReports", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.NormalizedSymbolRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalSymbolId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSynchronizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkageBasis")
                        .HasColumnType("text");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SymbolCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SymbolCode");

                    b.HasIndex("ProviderName", "ExternalSymbolId")
                        .IsUnique();

                    b.ToTable("Symbols", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.StockMarketSyncStateRow", b =>
                {
                    b.Property<string>("Dataset")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContinuationExternalId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ContinuationWatermark")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastRunCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastRunStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("Watermark")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Dataset");

                    b.ToTable("StockMarketSyncStates", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.TradingInstrumentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExternalInstrumentId")
                        .HasColumnType("uuid");

                    b.Property<long>("InstrumentCode")
                        .HasColumnType("bigint");

                    b.Property<string>("InstrumentIsin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstrumentKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSynchronizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("NormalizedCompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SourceChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedCompanyId");

                    b.HasIndex("ProviderName", "ExternalInstrumentId")
                        .IsUnique();

                    b.HasIndex("ProviderName", "InstrumentCode")
                        .IsUnique();

                    b.ToTable("TradingInstruments", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.WatchlistSymbolRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ActorId", "ActorType", "Position");

                    b.HasIndex("TenantId", "ActorId", "ActorType", "Symbol")
                        .IsUnique();

                    b.ToTable("WatchlistSymbols", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.DailyIndexSnapshotRow", b =>
                {
                    b.HasOne("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.TradingInstrumentRow", null)
                        .WithMany()
                        .HasForeignKey("TradingInstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.DailyInstrumentTradeRow", b =>
                {
                    b.HasOne("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.TradingInstrumentRow", null)
                        .WithMany()
                        .HasForeignKey("TradingInstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.IntradayIndexSnapshotRow", b =>
                {
                    b.HasOne("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.TradingInstrumentRow", null)
                        .WithMany()
                        .HasForeignKey("TradingInstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.IntradayTradeSnapshotRow", b =>
                {
                    b.HasOne("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.TradingInstrumentRow", null)
                        .WithMany()
                        .HasForeignKey("TradingInstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.LatestMarketQuoteRow", b =>
                {
                    b.HasOne("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.TradingInstrumentRow", null)
                        .WithMany()
                        .HasForeignKey("TradingInstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.NormalizedCompanyRow", b =>
                {
                    b.HasOne("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.NormalizedIndustryGroupRow", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.NormalizedIndustryRow", null)
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.NormalizedMarketRow", null)
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.NormalizedIndustryRow", b =>
                {
                    b.HasOne("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.NormalizedIndustryRow", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.TradingInstrumentRow", b =>
                {
                    b.HasOne("FinancialCopilot.Infrastructure.Financial.Ingestion.Persistence.NormalizedCompanyRow", null)
                        .WithMany()
                        .HasForeignKey("NormalizedCompanyId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
