// <auto-generated />
using System;
using FinancialCopilot.Infrastructure.Billing.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinancialCopilot.Infrastructure.Billing.Persistence.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    partial class BillingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Billing.Persistence.BillingAdminAuditRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("After")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Before")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OccurredAt");

                    b.ToTable("billing_admin_audits", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Billing.Persistence.BillingOutboxMessageRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ProcessedAt", "OccurredAt");

                    b.ToTable("billing_outbox_messages", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Billing.Persistence.CustomerAccountRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BillingMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("CreditLineApprovedLimit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("CreditLineWarningThreshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset?>("SubscriptionEffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SubscriptionEffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubscriptionPlanCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SubscriptionRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanCode");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique();

                    b.ToTable("billing_customer_accounts", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Billing.Persistence.DailyFreeAllowanceGrantRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("AllowanceDateKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("CustomerAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExpiredCredits")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LedgerEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LedgerEntryId");

                    b.HasIndex("ExpiresAtUtc", "ExpiredAtUtc");

                    b.HasIndex("CustomerAccountId", "ActorId", "AllowanceDateKey", "PolicyVersion")
                        .IsUnique();

                    b.ToTable("billing_daily_free_allowance_grants", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Billing.Persistence.FinancialTransactionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("CustomerAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("billing_financial_transactions", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Billing.Persistence.InvoiceAccountRow", b =>
                {
                    b.Property<Guid>("CustomerAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingEmail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("SettlementTerms")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("CustomerAccountId");

                    b.ToTable("billing_invoice_accounts", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Billing.Persistence.PlanCapabilityRow", b =>
                {
                    b.Property<string>("PlanCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CapabilityCode")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("PolicyVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Limit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("PlanCode", "CapabilityCode", "PolicyVersion");

                    b.ToTable("billing_plan_capabilities", (string)null);

                    b.HasData(
                        new
                        {
                            PlanCode = "Free",
                            CapabilityCode = "AiQuery.Scanner",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 10m
                        },
                        new
                        {
                            PlanCode = "Free",
                            CapabilityCode = "AiQuery.StockAnalysis",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 5m
                        },
                        new
                        {
                            PlanCode = "Free",
                            CapabilityCode = "AiQuery.FinancialComparison",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 5m
                        },
                        new
                        {
                            PlanCode = "Free",
                            CapabilityCode = "Reports.Read",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 100m
                        },
                        new
                        {
                            PlanCode = "Free",
                            CapabilityCode = "Watchlist.Symbols",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 5m
                        },
                        new
                        {
                            PlanCode = "Free",
                            CapabilityCode = "Tracker.Rules",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 3m
                        },
                        new
                        {
                            PlanCode = "Free",
                            CapabilityCode = "Radar.Symbols",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 5m
                        },
                        new
                        {
                            PlanCode = "Free",
                            CapabilityCode = "MarketPulse.Read",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Free",
                            CapabilityCode = "Notifications.Telegram",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Pro",
                            CapabilityCode = "AiQuery.Scanner",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Pro",
                            CapabilityCode = "AiQuery.StockAnalysis",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Pro",
                            CapabilityCode = "AiQuery.FinancialComparison",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Pro",
                            CapabilityCode = "AiQuery.CodalAnalysis",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 30m
                        },
                        new
                        {
                            PlanCode = "Pro",
                            CapabilityCode = "AiQuery.PortfolioAnalysis",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 10m
                        },
                        new
                        {
                            PlanCode = "Pro",
                            CapabilityCode = "Reports.Read",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Pro",
                            CapabilityCode = "Watchlist.Symbols",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 20m
                        },
                        new
                        {
                            PlanCode = "Pro",
                            CapabilityCode = "Portfolio.Records",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 10m
                        },
                        new
                        {
                            PlanCode = "Pro",
                            CapabilityCode = "Tracker.Rules",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 20m
                        },
                        new
                        {
                            PlanCode = "Pro",
                            CapabilityCode = "Radar.Symbols",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 20m
                        },
                        new
                        {
                            PlanCode = "Pro",
                            CapabilityCode = "MarketPulse.Read",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Pro",
                            CapabilityCode = "AiQuery.PersonalDigest",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 30m
                        },
                        new
                        {
                            PlanCode = "Pro",
                            CapabilityCode = "Notifications.Telegram",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Plus",
                            CapabilityCode = "AiQuery.Scanner",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Plus",
                            CapabilityCode = "AiQuery.StockAnalysis",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Plus",
                            CapabilityCode = "AiQuery.FinancialComparison",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Plus",
                            CapabilityCode = "AiQuery.CodalAnalysis",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Plus",
                            CapabilityCode = "AiQuery.DeepResearch",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 10m
                        },
                        new
                        {
                            PlanCode = "Plus",
                            CapabilityCode = "AiQuery.PortfolioAnalysis",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 50m
                        },
                        new
                        {
                            PlanCode = "Plus",
                            CapabilityCode = "Reports.Read",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Plus",
                            CapabilityCode = "Watchlist.Symbols",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 50m
                        },
                        new
                        {
                            PlanCode = "Plus",
                            CapabilityCode = "Portfolio.Records",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 50m
                        },
                        new
                        {
                            PlanCode = "Plus",
                            CapabilityCode = "Tracker.Rules",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 50m
                        },
                        new
                        {
                            PlanCode = "Plus",
                            CapabilityCode = "Radar.Symbols",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 50m
                        },
                        new
                        {
                            PlanCode = "Plus",
                            CapabilityCode = "MarketPulse.Read",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Plus",
                            CapabilityCode = "AiQuery.PersonalDigest",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Plus",
                            CapabilityCode = "Notifications.Telegram",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Premium",
                            CapabilityCode = "AiQuery.Scanner",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Premium",
                            CapabilityCode = "AiQuery.StockAnalysis",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Premium",
                            CapabilityCode = "AiQuery.FinancialComparison",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Premium",
                            CapabilityCode = "AiQuery.CodalAnalysis",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Premium",
                            CapabilityCode = "AiQuery.DeepResearch",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Premium",
                            CapabilityCode = "AiQuery.PortfolioAnalysis",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Premium",
                            CapabilityCode = "Reports.Read",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Premium",
                            CapabilityCode = "Watchlist.Symbols",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 100m
                        },
                        new
                        {
                            PlanCode = "Premium",
                            CapabilityCode = "Portfolio.Records",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 100m
                        },
                        new
                        {
                            PlanCode = "Premium",
                            CapabilityCode = "Tracker.Rules",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 100m
                        },
                        new
                        {
                            PlanCode = "Premium",
                            CapabilityCode = "Radar.Symbols",
                            PolicyVersion = "v1",
                            IsEnabled = true,
                            Limit = 100m
                        },
                        new
                        {
                            PlanCode = "Premium",
                            CapabilityCode = "MarketPulse.Read",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Premium",
                            CapabilityCode = "AiQuery.PersonalDigest",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        },
                        new
                        {
                            PlanCode = "Premium",
                            CapabilityCode = "Notifications.Telegram",
                            PolicyVersion = "v1",
                            IsEnabled = true
                        });
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Billing.Persistence.SubscriptionPlanRow", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("IncludedCredits")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("PricingPolicyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Code");

                    b.ToTable("billing_subscription_plans", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "Free",
                            IncludedCredits = 10000m,
                            Name = "Free",
                            PricingPolicyVersion = "v1"
                        },
                        new
                        {
                            Code = "Pro",
                            IncludedCredits = 100m,
                            Name = "Pro",
                            PricingPolicyVersion = "v1"
                        },
                        new
                        {
                            Code = "Plus",
                            IncludedCredits = 300m,
                            Name = "Plus",
                            PricingPolicyVersion = "v1"
                        },
                        new
                        {
                            Code = "Premium",
                            IncludedCredits = 1000m,
                            Name = "Premium",
                            PricingPolicyVersion = "v1"
                        });
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Billing.Persistence.UsageLedgerEntryRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("AllocationSource")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("AllowanceDateKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ApiClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuditDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CompletionStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<decimal>("CreditsCharged")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("CustomerAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("EstimatedCost")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("ExternalUserId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("ModelName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperationCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PricingPolicyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("RelatedEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("RelatedEntryId");

                    b.HasIndex("CustomerAccountId", "OccurredAt");

                    b.ToTable("billing_usage_ledger_entries", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Billing.Persistence.UsageReservationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CommittedCredits")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FinalizationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("OperationCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("ReservedCredits")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("billing_usage_reservations", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Billing.Persistence.WalletProjectionRow", b =>
                {
                    b.Property<Guid>("CustomerAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("ReservedAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CustomerAccountId");

                    b.ToTable("billing_wallet_projections", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Billing.Persistence.CustomerAccountRow", b =>
                {
                    b.HasOne("FinancialCopilot.Infrastructure.Billing.Persistence.SubscriptionPlanRow", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionPlanCode")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Billing.Persistence.DailyFreeAllowanceGrantRow", b =>
                {
                    b.HasOne("FinancialCopilot.Infrastructure.Billing.Persistence.CustomerAccountRow", null)
                        .WithMany()
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancialCopilot.Infrastructure.Billing.Persistence.UsageLedgerEntryRow", null)
                        .WithMany()
                        .HasForeignKey("LedgerEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Billing.Persistence.PlanCapabilityRow", b =>
                {
                    b.HasOne("FinancialCopilot.Infrastructure.Billing.Persistence.SubscriptionPlanRow", null)
                        .WithMany()
                        .HasForeignKey("PlanCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
