<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f5b4695b-0a6b-4c84-bd45-7767191d459d</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FinancialCopilot.Application\FinancialCopilot.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="FinancialCopilot.UnitTests" />
  </ItemGroup>
</Project>
