import { Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { adminApi, type FundPortfolioReport, type FundPortfolioReview, type FundPortfolioRun } from "@/integrations/financial-copilot/admin-client";
import { Activity, Archive, ArrowRight, BarChart2, Database, GitCompare } from "lucide-react";

type SourceCard = { title: string; vendor: string; source: string; mode: string; description: string; to: string; icon: React.ComponentType<{ className?: string }>; badge?: { label: string; cls: string } };

const sources: SourceCard[] = [
  { title: "آرشیو نواوران امین", vendor: "NoavaranAmin", source: "NoavaranArchiveSql", mode: "ArchiveOneTime", description: "تصویر ثابت SQL از CodalDB؛ یک‌بار وارد، اعتبارسنجی و نهایی می‌شود و زمان‌بندی ندارد.", to: "/admin/data/archive", icon: Archive, badge: { label: "آرشیو", cls: "bg-blue-500/15 text-blue-600" } },
  { title: "رابط فعلی نواوران", vendor: "NoavaranAmin", source: "NoavaranCurrentApi", mode: "CurrentIncremental", description: "همگام‌سازی افزایشی دوره‌ای از سال ۱۴۰۳ به بعد از طریق API نواوران.", to: "/admin/data/noavaran", icon: BarChart2, badge: { label: "زنده", cls: "bg-emerald-500/15 text-emerald-600" } },
  { title: "رابط CyclicalWaves", vendor: "CyclicalWaves", source: "CyclicalWavesApi", mode: "ExternalSnapshot", description: "منبع مستقل داده‌های بنیادی با همگام‌سازی دوره‌ای تصویر کامل.", to: "/admin/data/noavaran", icon: BarChart2, badge: { label: "تصویر کامل", cls: "bg-purple-500/15 text-purple-600" } },
  { title: "پل StockMarketDB", vendor: "Tsetmc", source: "StockMarketDb", mode: "MigrationBridge", description: "داده‌های معاملات بازار از طریق پل فقط‌خواندنی SQL Server؛ راهکاری موقت تا جایگزینی با خوراک مستقیم TSETMC.", to: "/admin/data/stockmarket", icon: Database, badge: { label: "پل", cls: "bg-amber-500/15 text-amber-600" } },
  { title: "خوراک مستقیم TSETMC", vendor: "Tsetmc", source: "TsetmcWebService", mode: "CurrentIncremental", description: "دریافت مستقیم از وب‌سرویس ASMX تی‌اس‌ای‌ام‌سی؛ هنوز عملیاتی نشده است.", to: "/admin/data/stockmarket", icon: Database, badge: { label: "برنامه‌ریزی‌شده", cls: "bg-muted text-muted-foreground" } },
];

export function DataManagementOverviewPage() {
  const [file, setFile] = useState<File | null>(null);
  const [fundName, setFundName] = useState("");
  const [runs, setRuns] = useState<FundPortfolioRun[]>([]);
  const [reports, setReports] = useState<FundPortfolioReport[]>([]);
  const [reviews, setReviews] = useState<FundPortfolioReview[]>([]);
  const [sourceStatus, setSourceStatus] = useState<{ available: boolean; unavailableReason: string | null } | null>(null);
  const [health, setHealth] = useState<{ sourceAvailable: boolean; sourceReason: string | null; totalRuns: number; queuedItems: number; retryableItems: number; pendingReviews: number; lastRunAtUtc: string | null } | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const refresh = () => Promise.all([adminApi.fundPortfolioRuns(), adminApi.fundPortfolioReports(), adminApi.fundPortfolioReviews(), adminApi.fundPortfolioSourceStatus(), adminApi.fundPortfolioHealth()]).then(([runPage, reportPage, reviewPage, status, healthPage]) => { setRuns(runPage.items); setReports(reportPage.items); setReviews(reviewPage.items); setSourceStatus(status); setHealth(healthPage); }).catch((error) => setMessage(error instanceof Error ? error.message : "بارگذاری عملیات پرتفوی صندوق ناموفق بود."));
  useEffect(() => { void refresh(); }, []);
  const upload = async () => { if (!file) return; try { const result = await adminApi.fundPortfolioUpload(file, fundName || undefined); setMessage(`اجرای ${result.runId} با ${result.itemCount} مورد در صف قرار گرفت.`); setFile(null); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "آپلود ناموفق بود."); } };
  const reprocess = async (report: FundPortfolioReport) => { if (!window.confirm(`پردازش مجدد ${report.originalFileName}؟`)) return; await adminApi.fundPortfolioReprocess(report.reportId); setMessage(`پردازش مجدد ${report.reportId} در صف قرار گرفت.`); await refresh(); };
  const resolve = async (review: FundPortfolioReview, approve: boolean) => { const resolution = window.prompt("JSON تصمیم", review.resolutionJson ?? "{}"); if (resolution === null) return; await adminApi.fundPortfolioResolveReview(review, approve, resolution); await refresh(); };

  return <div dir="rtl" className="space-y-6">
    <div><h1 className="text-xl font-bold">عملیات داده</h1><p className="text-sm text-muted-foreground mt-1">مدیریت ورود آرشیوها، همگام‌سازی APIهای فعلی، منابع داده بازار و پایش زنده.</p></div>
    <section className="rounded-xl border border-border bg-surface/60 p-4 space-y-4">
      <div className="flex items-center justify-between gap-3"><div><h2 className="text-sm font-semibold">ورود اطلاعات پرتفوی صندوق</h2><p className="text-xs text-muted-foreground mt-1">آپلود فایل‌های تأییدشده، پایش اجراها، بررسی نگاشت‌ها و پردازش مجدد گزارش‌ها.</p></div><span className={`text-xs rounded-full px-2 py-1 ${sourceStatus?.available ? "bg-emerald-500/15 text-emerald-600" : "bg-amber-500/15 text-amber-600"}`}>{sourceStatus?.available ? "رابط منبع آماده است" : sourceStatus?.unavailableReason ?? "در حال بررسی رابط منبع"}</span></div>
      <div className="flex flex-wrap items-center gap-2"><input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(event) => setFile(event.target.files?.[0] ?? null)} className="text-xs" /><input value={fundName} onChange={(event) => setFundName(event.target.value)} placeholder="راهنمای نام صندوق" className="rounded border border-border bg-background px-2 py-1 text-xs" /><button type="button" disabled={!file} onClick={() => void upload()} className="rounded bg-primary px-3 py-1.5 text-xs text-primary-foreground disabled:opacity-50">قرار دادن در صف آپلود</button>{message && <span className="text-xs text-muted-foreground">{message}</span>}</div>
      <div className="grid grid-cols-1 xl:grid-cols-2 gap-4"><div><h3 className="text-xs font-semibold mb-2">اجراهای اخیر</h3><div className="space-y-1">{runs.map((run) => <div key={run.id} className="flex justify-between rounded border border-border px-2 py-1.5 text-xs"><span>{run.status} · {run.triggerType}</span><span>{run.importedCount}/{run.discoveredCount} وارد شده</span></div>)}{runs.length === 0 && <p className="text-xs text-muted-foreground">اجرایی یافت نشد.</p>}</div></div><div><h3 className="text-xs font-semibold mb-2">گزارش‌ها و خطاها</h3><div className="space-y-1">{reports.map((report) => <div key={report.reportId} className="flex items-center justify-between gap-2 rounded border border-border px-2 py-1.5 text-xs"><span className="truncate">{report.originalFileName} · {report.parseStatus} · {report.issueCount} خطا</span><button type="button" onClick={() => void reprocess(report)} className="shrink-0 text-primary hover:underline">پردازش مجدد</button></div>)}{reports.length === 0 && <p className="text-xs text-muted-foreground">گزارشی یافت نشد.</p>}</div></div></div>
      <div><h3 className="text-xs font-semibold mb-2">بررسی نگاشت‌های در انتظار</h3><div className="space-y-1">{reviews.map((review) => <div key={review.id} className="flex items-center justify-between gap-2 rounded border border-border px-2 py-1.5 text-xs"><span className="truncate">{review.mappingType} · {review.rawValue}</span><span className="flex gap-2"><button type="button" onClick={() => void resolve(review, true)} className="text-emerald-600 hover:underline">تأیید</button><button type="button" onClick={() => void resolve(review, false)} className="text-destructive hover:underline">رد</button></span></div>)}{reviews.length === 0 && <p className="text-xs text-muted-foreground">نگاشت در انتظاری وجود ندارد.</p>}</div></div>
    </section>
    {health && <section className="grid grid-cols-2 md:grid-cols-5 gap-3"><Metric label="اجراها" value={health.totalRuns} /><Metric label="در صف" value={health.queuedItems} /><Metric label="قابل تکرار" value={health.retryableItems} /><Metric label="بررسی‌ها" value={health.pendingReviews} /><Metric label="منبع" value={health.sourceAvailable ? "آماده" : "در دسترس نیست"} /></section>}
    <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-4">{sources.map(({ title, vendor, source, mode, description, to, icon: Icon, badge }) => <Link key={source} to={to} className="group rounded-xl border border-border bg-surface/60 p-4 hover:border-primary/40 hover:bg-primary/5 transition-colors flex flex-col gap-3"><div className="flex items-start justify-between gap-2"><div className="rounded-lg bg-muted p-2"><Icon className="size-4 text-foreground" /></div>{badge && <span className={`text-[10px] font-medium px-2 py-0.5 rounded-full ${badge.cls}`}>{badge.label}</span>}</div><div className="flex-1"><h2 className="text-sm font-semibold group-hover:text-primary transition-colors">{title}</h2><p className="text-xs text-muted-foreground mt-1 line-clamp-2">{description}</p></div><div className="text-xs text-muted-foreground space-y-0.5"><div><span className="font-mono">{vendor}</span> / <span className="font-mono">{source}</span></div><div className="text-[10px] opacity-70 font-mono">{mode}</div></div><div className="flex items-center gap-1 text-xs text-primary opacity-0 group-hover:opacity-100 transition-opacity">مشاهده <ArrowRight className="size-3" /></div></Link>)}</div>
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Link to="/admin/data/monitor" className="group rounded-xl border border-border bg-surface/60 p-4 hover:border-primary/40 hover:bg-primary/5 transition-colors flex items-center gap-4"><div className="rounded-lg bg-emerald-500/10 p-3"><Activity className="size-5 text-emerald-600" /></div><div className="flex-1"><h2 className="text-sm font-semibold group-hover:text-primary transition-colors">پایش زنده</h2><p className="text-xs text-muted-foreground">نمایش لحظه‌ای فعالیت همگام‌سازی همه ارائه‌دهندگان.</p></div><ArrowRight className="size-4 text-muted-foreground group-hover:text-primary transition-colors" /></Link><Link to="/admin/data/reconciliation" className="group rounded-xl border border-border bg-surface/60 p-4 hover:border-primary/40 hover:bg-primary/5 transition-colors flex items-center gap-4"><div className="rounded-lg bg-purple-500/10 p-3"><GitCompare className="size-5 text-purple-600" /></div><div className="flex-1"><h2 className="text-sm font-semibold group-hover:text-primary transition-colors">تطبیق داده‌ها</h2><p className="text-xs text-muted-foreground">پوشش منابع، تعارض‌ها، داده‌های قدیمی و دوره‌های ناقص.</p></div><ArrowRight className="size-4 text-muted-foreground group-hover:text-primary transition-colors" /></Link></div>
    <div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-4 flex gap-3"><p className="text-xs text-amber-600">منبع <strong>StockMarketDB</strong> یک <strong>پل مهاجرتی</strong> است. در آینده خوراک مستقیم وب‌سرویس TSETMC جایگزین آن می‌شود؛ تا آن زمان StockMarketDB منبع مرجع داده‌های بازار است.</p></div>
  </div>;
}

function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl border border-border bg-surface/60 p-3"><div className="text-[10px] uppercase tracking-wide text-muted-foreground">{label}</div><div className="text-lg font-semibold mt-1">{value}</div></div>; }
