// <auto-generated />
using System;
using FinancialCopilot.Infrastructure.Financial.Providers.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinancialCopilot.Infrastructure.Financial.Providers.Persistence.Migrations
{
    [DbContext(typeof(FinancialProviderDbContext))]
    [Migration("20260801082426_AddFundPortfolioMappingReviewConcurrency")]
    partial class AddFundPortfolioMappingReviewConcurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Providers.Persistence.FundPortfolioExtractionIssueRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssueCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ParserProfileVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RawValue")
                        .HasColumnType("text");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SheetId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceAddress")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IssueCode");

                    b.HasIndex("ReportId", "Severity");

                    b.HasIndex("Severity", "IssueCode");

                    b.ToTable("FundPortfolioExtractionIssues", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Providers.Persistence.FundPortfolioImportItemRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DownloadToken")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("FileSha256")
                        .HasColumnType("text");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastErrorSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ObservedFundName")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ObservedPeriodEnd")
                        .HasColumnType("date");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceObjectId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId");

                    b.HasIndex("ProviderName", "FileSha256")
                        .IsUnique()
                        .HasFilter("\"FileSha256\" IS NOT NULL");

                    b.HasIndex("ProviderName", "SourceObjectId")
                        .IsUnique()
                        .HasFilter("\"SourceObjectId\" IS NOT NULL");

                    b.HasIndex("Status", "AttemptCount", "StartedAtUtc");

                    b.ToTable("FundPortfolioImportItems", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Providers.Persistence.FundPortfolioImportRunRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("DiscoveredCount")
                        .HasColumnType("integer");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("integer");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("ImportedCount")
                        .HasColumnType("integer");

                    b.Property<int>("PartialCount")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RequestedByActorId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TriggerType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProviderName");

                    b.HasIndex("Status", "StartedAtUtc");

                    b.ToTable("FundPortfolioImportRuns", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Providers.Persistence.FundPortfolioMappingReviewRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CandidateJson")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<int>("MappingType")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RawValue")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResolutionJson")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedByActorId")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.HasIndex("Status", "MappingType");

                    b.ToTable("FundPortfolioMappingReviews", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Providers.Persistence.FundPortfolioReportRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalReportId")
                        .HasColumnType("text");

                    b.Property<string>("FileSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FiscalYearEndJalali")
                        .HasColumnType("text");

                    b.Property<string>("FiscalYearStartJalali")
                        .HasColumnType("text");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("ParseStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ParserProfileVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateOnly?>("PeriodEndDate")
                        .HasColumnType("date");

                    b.Property<string>("PeriodEndJalali")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("PeriodStartDate")
                        .HasColumnType("date");

                    b.Property<string>("PeriodStartJalali")
                        .HasColumnType("text");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("RawFileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("RawMimeType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RawStorageKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("ReportType")
                        .HasColumnType("integer");

                    b.Property<int>("SourceRevision")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SupersedesReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParseStatus");

                    b.HasIndex("ProviderName");

                    b.HasIndex("FundId", "PeriodEndDate");

                    b.HasIndex("ProviderName", "FileSha256")
                        .IsUnique();

                    b.HasIndex("FundId", "ProviderName", "PeriodEndDate", "ReportType", "SourceRevision")
                        .IsUnique();

                    b.ToTable("FundPortfolioReports", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Providers.Persistence.FundPortfolioReportSheetRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ClassificationConfidence")
                        .HasColumnType("numeric");

                    b.Property<string>("HeaderFingerprint")
                        .HasColumnType("text");

                    b.Property<int>("LogicalSheetType")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedSheetName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OriginalSheetName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ParserProfileVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<int>("SheetIndex")
                        .HasColumnType("integer");

                    b.Property<string>("UsedRange")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LogicalSheetType");

                    b.HasIndex("ReportId", "SheetIndex")
                        .IsUnique();

                    b.ToTable("FundPortfolioReportSheets", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Providers.Persistence.InvestmentFundRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalFundId")
                        .HasColumnType("text");

                    b.Property<string>("FundName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("FundSymbol")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ManagerName")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedFundName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderName", "ExternalFundId")
                        .IsUnique()
                        .HasFilter("\"ExternalFundId\" IS NOT NULL");

                    b.HasIndex("ProviderName", "NormalizedFundName");

                    b.ToTable("InvestmentFunds", (string)null);
                });

            modelBuilder.Entity("FinancialCopilot.Infrastructure.Financial.Providers.Persistence.ProviderRawPayloadRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Dataset")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderName", "Checksum")
                        .IsUnique();

                    b.ToTable("ProviderRawPayloads", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
